# -*- coding: utf-8 -*-
"""Chernetska_DA6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b-hCOKp_1GjE2bxQ68bMlquFkNjn3xwd
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans

df = pd.read_csv('global_ai_jobs.csv')

df.info()

df.describe()

missing_data = df.isnull()
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

st.set_page_config(
    page_title="AI Salary Dashboard",
    page_icon="💰",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Бічна панель / SIDEBAR
st.sidebar.title("Панель фільтрації")

selected_year = st.sidebar.selectbox("Рік аналізу", options=sorted(df["year"].unique(), reverse=True))
selected_level = st.sidebar.multiselect("Рівень досвіду", options=df["experience_level"].unique(), default=df["experience_level"].unique())
selected_roles = st.sidebar.multiselect("Професійні ролі", df["job_role"].unique(), default=df["job_role"].unique())
selected_mode = st.sidebar.radio("Формат роботи", df["work_mode"].unique())
selected_industries = st.sidebar.multiselect("Галузі економіки", options=df["industry"].unique(), default=df["industry"].unique())

selected_max_exp = st.sidebar.slider(
    "Максимальний стаж (роки)",
    min_value=int(df["experience_years"].min()),
    max_value=int(df["experience_years"].max()),
    value=int(df["experience_years"].max())
)

chart_option = st.sidebar.radio(
    "📈 Оберіть аналітичний розріз:",
    [
        "Розподіл зарплат (Histogram)",
        "Зарплата за рівнем досвіду (Boxplot)",
        "Топ-10 професій за зарплатою",
        "Матриця кореляції (Heatmap)",
        "Кластеризація: Дохід vs Досвід (KMeans)"
    ]
)

st.sidebar.markdown("---")
st.sidebar.markdown("**Інструкція**: Виберіть параметри зліва, щоб побачити аналітику зарплат у реальному часі.")
st.sidebar.markdown(" **Автор**: Chernetska_Ilona")

df_filtered = df[
    (df["year"] == selected_year) &
    (df["experience_level"].isin(selected_level)) &
    (df["job_role"].isin(selected_roles)) &
    (df["work_mode"] == selected_mode) &
    (df["industry"].isin(selected_industries)) &
    (df["experience_years"] <= selected_max_exp)
]

# Блок регресії
st.sidebar.markdown("---")

all_numeric = df_filtered.select_dtypes(include=np.number).columns.tolist()
numeric_columns = [col for col in all_numeric if col not in ['id', 'year']]

reg_x = st.sidebar.selectbox("Оберіть змінну X (Досвід)", numeric_columns)
reg_y = st.sidebar.selectbox("Оберіть змінну Y (Зарплата)", numeric_columns)
show_regression = st.sidebar.checkbox("Побудувати регресійну модель")

# Основна панель
st.title("📊 Аналіз зарплат у сфері AI та Data")
st.subheader(f"🔍 Відфільтровано {df_filtered.shape[0]} записів")

# Кнопка завантаження CSV
csv = df_filtered.to_csv(index=False).encode("utf-8")
st.download_button(
    label="⬇️ Завантажити результати у CSV",
    data=csv,
    file_name="ai_salary_filtered.csv",
    mime="text/csv"
)

# Інтерактивна таблиця результатів
st.subheader("Таблиця даних")

all_columns = df_filtered.columns.tolist()
default_columns = ["country", "job_role", "experience_level", "salary_usd", "industry"]

selected_columns = st.multiselect(
    "Оберіть стовпці для відображення",
    options=all_columns,
    default=[col for col in default_columns if col in all_columns]
)

if selected_columns:
    st.dataframe(df_filtered[selected_columns], use_container_width=True)
else:
    st.info("Оберіть хоча б один стовпець, щоб побачити таблицю.")

st.divider()

# Відображення обраного графіка
if chart_option == "Топ-10 професій за зарплатою":
    st.subheader("📊 Середня зарплата за професіями")
    avg_salary_role = df_filtered.groupby("job_role")["salary_usd"].mean().sort_values(ascending=False).head(10).reset_index()
    fig = px.bar(avg_salary_role, x="salary_usd", y="job_role", orientation='h', labels={"salary_usd": "Середня ЗП ($)", "job_role": "Професія"}, color="salary_usd", color_continuous_scale="Viridis"
    )
    st.plotly_chart(fig, width="stretch")

elif chart_option == "Розподіл зарплат (Histogram)":
    st.subheader("📊 Розподіл зарплат фахівців")
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.histplot(df_filtered["salary_usd"], bins=30, kde=True, ax=ax, color='skyblue')
    ax.set_title("Гістограма зарплат (USD)")
    st.pyplot(fig)

elif chart_option == "Зарплата за рівнем досвіду (Boxplot)":
    st.subheader("📊 Розподіл зарплат за грейдами")
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.boxplot(data=df_filtered, x="experience_level", y="salary_usd", ax=ax, palette="Set2")
    ax.set_title("Зарплата в розрізі досвіду (Entry, Mid, Senior, Executive)")
    st.pyplot(fig)

elif chart_option == "Матриця кореляції (Heatmap)":
    st.subheader("📊 Кореляція числових показників")
    numeric_cols = df_filtered.select_dtypes(include=[np.number])
    cols_to_corr = [c for c in numeric_cols.columns if c not in ['id', 'year']]
    corr = numeric_cols[cols_to_corr].corr()
    fig, ax = plt.subplots(figsize=(12, 8))
    sns.heatmap(corr, annot=False, cmap="coolwarm", ax=ax)
    ax.set_title("Теплова карта взаємозв'язків між метриками")
    st.pyplot(fig)

elif chart_option == "Кластеризація: Дохід vs Досвід (KMeans)":
    st.subheader("📊 Кластеризація фахівців на основі доходу та досвіду")
    cluster_data = df_filtered[["experience_years", "salary_usd"]].dropna().copy()

    if cluster_data.shape[0] >= 3:
        kmeans = KMeans(n_clusters=3, random_state=0)
        cluster_data["Cluster"] = kmeans.fit_predict(cluster_data)

        chart = alt.Chart(cluster_data).mark_circle(size=60).encode(
            x="experience_years:Q",
            y="salary_usd:Q",
            color="Cluster:N",
            tooltip=["experience_years", "salary_usd", "Cluster"]
        ).interactive().properties(title="Кластеризація за Досвідом та Доходом")
        st.altair_chart(chart, use_container_width=True)
    else:
        st.warning("Недостатньо даних для кластеризації (потрібно ≥ 3 рядки).")

# Побудова регресійної моделі
if show_regression:
    st.divider()
    st.subheader(f"📈 Лінійна регресія: {reg_y} ~ {reg_x}")

    df_reg = df_filtered[[reg_x, reg_y]].dropna()

    if df_reg.shape[0] >= 2:
        model = LinearRegression()
        model.fit(df_reg[[reg_x]], df_reg[reg_y])
        y_pred = model.predict(df_reg[[reg_x]])

        coef = model.coef_[0]
        intercept = model.intercept_
        r2 = model.score(df_reg[[reg_x]], df_reg[reg_y])

        st.markdown(f"**Коефіцієнт нахилу (β):** {coef:.4f}")
        st.markdown(f"**Зсув (intercept):** {intercept:.4f}")
        st.markdown(f"**R²:** {r2:.4f}")

        fig, ax = plt.subplots(figsize=(8, 5))
        sns.scatterplot(data=df_reg, x=reg_x, y=reg_y, ax=ax, label="Фактичні дані")
        sns.lineplot(x=df_reg[reg_x], y=y_pred, color='red', ax=ax, label="Лінія регресії")
        ax.set_title(f"Регресія {reg_y} ~ {reg_x}")
        st.pyplot(fig)
    else:
        st.warning("Недостатньо даних для побудови регресії.")